export const MODEL_PERSON_COUPLE = 500;
export const MODEL_PERSON_MAID_OF_HONOR = 501;
export const MODEL_PERSON_BRIDESMAID = 502;
export const MODEL_PERSON_BEST_MAN = 503;
export const MODEL_PERSON_GROOMSMAN = 504;
export const MODEL_PERSON_FLOWER_GIRL = 505;
export const MODEL_PERSON_PAGE_BOY = 506;
export const MODEL_PERSON_RING_BEARER= 507;